### ISSUE TITLE
what are argumets parameters used for sift function

### ISSUE THREAD

**Issue by millermuttu** [nbarba/py3DRec#4]
hi,

i am not able to reproduce the same result for poster example using my sift function, can you please tell me the argument parameters used for sift function like,
nfeatures
nOctaveLayers
contrastThreshold
edgeThreshold
sigma

**Comment by nbarba** [comment]
Hi there, 
It has been a while (10+ years) since I run sift to get those points so I do not remember any of the parameters. It was not on OpenCV but on my own c++ implementation of sift, so it's impossible to track this down (I do not have that code anymore).
But playing around with the parameters and preprocessing your images should give you what you are looking for; sift is known to produce good results for those types of problems

**Comment by millermuttu** [comment]
i tried a lot and failed to reproduce it,

anyway thanks for ur reply.

i will try again.
